# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created, updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: json-chatbot
          path: json-chatbot-*.tgz
      - run: npm ci
      - run: npm run build:ci
      - run: cd dist/json-chatbot
      - run: npm pack

  publish:
    needs: build-pack
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: cd dist/json-chatbot
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
